/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Action;

import Entities.Client;
import Entities.DataPerson;
import Entities.Materials;
import Entities.Selling;
import Entities.SellingMaterials;
import Entities.co_worker;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Material;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Kathy
 */
public class ToOder extends javax.swing.JDialog {

    Connection c;
    SellingMaterials editItem;
    List<DataPerson> list;
    List<Materials> list1;
    List<DataPerson> list2;

    /**
     * Creates new form ToOder
     */
    public ToOder(java.awt.Frame parent, boolean modal, Connection c) {
        super(parent, modal);
        initComponents();
        this.c = c;

        comBox();
    }

    public ToOder(java.awt.Frame parent, boolean modal, Connection c, SellingMaterials ms) {
        super(parent, modal);
        initComponents();
        this.c = c;
        this.c = c;
        editItem = ms;

        comBox();
    }

    private void comBox() {

        list = new ArrayList<>();
        list1 = new ArrayList<>();
        list2 = new ArrayList<>();

        try {
            Statement statement = c.createStatement();
            ResultSet rs = statement.executeQuery("select id_dp, surname, firstname,"
                    + " otchestvo, passport,birthday,address,phone from co_worker left join "
                    + "data_person on data_person.id_dp = co_worker.fk_dp_cw");
            while (rs.next()) {
                DataPerson item = new DataPerson(rs.getInt("id_dp"), rs.getString("surname"),
                        rs.getString("firstname"), rs.getString("otchestvo"),
                        rs.getString("passport"), rs.getDate("birthday"), rs.getString("address"),
                        rs.getString("phone"));

                list.add(item);
            }
            worker.setModel(new DefaultComboBoxModel(list.toArray()));

            rs = statement.executeQuery("select id_dp, surname, firstname,"
                    + " otchestvo, passport,birthday,address,phone from client left join "
                    + " data_person on data_person.id_dp = client.fk_dp_client");
            while (rs.next()) {
                DataPerson item = new DataPerson(rs.getInt("id_dp"), rs.getString("surname"),
                        rs.getString("firstname"), rs.getString("otchestvo"),
                        rs.getString("passport"), rs.getDate("birthday"), rs.getString("address"),
                        rs.getString("phone"));
                list2.add(item);
            }
            client.setModel(new DefaultComboBoxModel(list2.toArray()));

            rs = statement.executeQuery("SELECT *   FROM materials ");
            while (rs.next()) {
                System.out.println("jhg");
                Materials item = new Materials(rs.getInt("id_materials"), rs.getString("name_materials"),
                        rs.getInt("amount_materials"), rs.getInt("price_materials"),
                        rs.getInt("fk_providers"));
                list1.add(item);
            }
            material.setModel(new DefaultComboBoxModel(list1.toArray()));
        } catch (SQLException ex) {
            Logger.getLogger(ToOder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        date = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        worker = new javax.swing.JComboBox<>();
        client = new javax.swing.JComboBox<>();
        material = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        num = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        worker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        material.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("to oder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("№ contracta");

        jLabel2.setText("Date");

        jLabel3.setText("Worker");

        jLabel4.setText("Client");

        jLabel5.setText("Product");

        jLabel6.setText("Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(material, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(worker, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(client, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(104, 104, 104)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(46, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel3)
                        .addGap(118, 118, 118)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel5)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(worker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(material, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            // TODO add your handling code here:
            Statement statement = c.createStatement();
            ResultSet rs = statement.executeQuery("select co_worker.id_cw as id from data_person,co_worker where data_person.id_dp=co_worker.fk_dp_cw and data_person.id_dp = "
                    + ((DataPerson) worker.getSelectedItem()).getId());
            int id_worker = 0;
            while (rs.next()) {
                id_worker = rs.getInt("id");
            }

            rs = statement.executeQuery("select client.id_client as id from data_person,client where data_person.id_dp=client.fk_dp_client and data_person.id_dp = "
                    + ((DataPerson) client.getSelectedItem()).getId());
            int id_client = 0;
            while (rs.next()) {
                id_client = rs.getInt("id");
            }
            statement.executeUpdate("insert into selling(number_contract,date_selling,fk_id_cw,fk_id_client) values("
                    + num.getText() + ",'" + date.getText() + "'," + id_worker + "," + id_client + ");");

            rs = statement.executeQuery("select  max(id_selling) as max from selling;");
            int id_sell = 0;
            while (rs.next()) {
                id_sell = rs.getInt("max");
            }
            statement.executeUpdate("insert into selling_materials(fk_id_selling,fk_id_materials,amount) values("
                    + id_sell + "," + ((Materials) material.getSelectedItem()).getId() + "," + amount.getText() + ");");

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());

            return;
        }
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox<String> client;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> material;
    private javax.swing.JTextField num;
    private javax.swing.JComboBox<String> worker;
    // End of variables declaration//GEN-END:variables
}
