/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EntitiesFrame;

import Entities.Client;
import Entities.DataPerson;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author Kathy
 */
public class AddClient extends javax.swing.JDialog {

    Connection c;
    Client editClient;
    List<DataPerson> list;

    /**
     * Creates new form AddClient
     */
    public AddClient(java.awt.Frame parent, boolean modal, Connection c) {
        super(parent, modal);
        initComponents();
        this.c = c;
        entryClient();

    }

    
    public AddClient(java.awt.Frame parent, boolean modal, Connection c, Client cl) {
        super(parent, modal);
        initComponents();
        this.c = c;
        editClient = cl;

        entryClient();

        fillFields();
    }

    private void fillFields() {

        jComboBox1.setSelectedItem(-1);

        for (DataPerson s : list) {
            if (s.getId() != editClient.getDataPId()) {
                jComboBox1.setSelectedItem((s));
            }
        }

    }
    private void entryClient() {
        list = new ArrayList<>();

        try {
            Statement statement = c.createStatement();

            ResultSet rs = statement.executeQuery("select id_dp, surname, firstname,"
                    + " otchestvo, passport,birthday,address,phone from data_person left join "
                    + "client on data_person.id_dp = client.fk_dp_client "
                    + "where client.id_client IS NULL");
            while (rs.next()) {
                DataPerson item = new DataPerson(rs.getInt("id_dp"), rs.getString("surname"),
                        rs.getString("firstname"), rs.getString("otchestvo"),
                        rs.getString("passport"), rs.getDate("birthday"), rs.getString("address"),
                        rs.getString("phone"));

                list.add(item);
            }
            jComboBox1.setModel(new DefaultComboBoxModel(list.toArray()));

        } catch (SQLException ex) {
            Logger.getLogger(AddData.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Client");

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            // TODO add your handling code here:
            Statement statement = c.createStatement();
            if (editClient == null) {

                statement.executeUpdate("insert into client (fk_dp_client) values ('" + ((DataPerson) jComboBox1.getSelectedItem()).getId() + "');");
            } else {
                statement.executeUpdate("update client set fk_dp_client='" + ((DataPerson) jComboBox1.getSelectedItem()).getId() + "' where id_client=" + editClient.getId() + ";");
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(new JFrame(), ex.getMessage());
            return;
        }
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
